# web binding
web:
  host: ""
  port: "80"

# 
telegram:
  botToken: "BOT:TOKEN"
  witChatID: -1234567890
  buildChatID: -1234567890
  deployChatID: -1234567890

excludedPipelines:
  build:
    - "pipeline1"
  release:
    - "pipeline11"
    - "pipeline23"